version: '3.8'
services:
  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_DB: time_tracking_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres-db:5432/time_tracking_db -user=user -password=password migrate
    depends_on:
      - postgres-db
    volumes:
      - ./sql:/flyway/sql

volumes:
  postgres-data:
